spring:
  application:
    name: demo
server:
  port: 8082
management:
  endpoint:
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: ['health', 'prometheus', 'metrics']